
# https://docs.docker.com/go/compose-spec-reference/
# https://github.com/docker/awesome-compose
services:
  # api:
  #   build:
  #     context: .
  #     target: final
#       restart: unless-stopped
  #   ports:
  #     - 8080:8080
#     depends_on:
#       db:
#         condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4:9.2.0
    container_name: typeneering_pgadmin
    secrets:
      - pgadmin-password
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.com
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin-password
      MAX_LOGIN_ATTEMPTS: 10
    ports:
      - 15432:80
    networks:
      - typeneering
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  db:
    image: postgres:17.4-alpine3.21
    container_name: typeneering_db
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=typeneering
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    networks:
      - typeneering
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  db-password:
    file: .secrets/database/password.txt

